"""Regenerates src/bundled_resources.rs from a uBlock Origin source checkout.

Usage:
    python3 tools/generate_resources.py /path/to/uBlock-Origin-source

Requires `node` on PATH. Pulls the real redirect-resource files and scriptlet
implementations straight out of uBO (by executing its own JS resource-registry
modules under Node, the same way uBO's own build tooling does) so the content
adblock-rust serves for `$redirect=` / `##+js(...)` matches upstream exactly,
rather than being hand-transcribed.
"""
import base64
import json
import os
import subprocess
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
CRATE_DIR = os.path.dirname(SCRIPT_DIR)
OUT_PATH = os.path.join(CRATE_DIR, "src", "bundled_resources.rs")


def rust_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def rust_str_vec(items) -> str:
    if not items:
        return "vec![]"
    return "vec![" + ", ".join(rust_str(x) + ".to_string()" for x in items) + "]"


def main():
    if len(sys.argv) != 2:
        print(__doc__)
        sys.exit(1)
    ubo_root = os.path.abspath(sys.argv[1])
    resources_dir = os.path.join(ubo_root, "src", "js", "resources")
    js_dir = os.path.join(ubo_root, "src", "js")
    war_dir = os.path.join(ubo_root, "src", "web_accessible_resources")

    scriptlets_out = os.path.join(SCRIPT_DIR, "_scriptlets.json")
    redirects_out = os.path.join(SCRIPT_DIR, "_redirects.json")

    subprocess.run(
        ["node", os.path.join(SCRIPT_DIR, "extract-scriptlets.mjs"), resources_dir, scriptlets_out],
        check=True,
    )
    subprocess.run(
        ["node", os.path.join(SCRIPT_DIR, "extract-redirects.mjs"), js_dir, redirects_out],
        check=True,
    )

    scriptlets = json.load(open(scriptlets_out))
    redirects = json.load(open(redirects_out))

    lines = []
    lines.append("// AUTO-GENERATED by tools/generate_resources.py. Do not edit by hand.")
    lines.append("//")
    lines.append("// Source data: uBlock Origin (https://github.com/gorhill/uBlock)")
    lines.append("//   - src/js/redirect-resources.js + src/web_accessible_resources/* (redirect stubs)")
    lines.append("//   - src/js/resources/scriptlets.js (scriptlets, extracted by executing uBO's own")
    lines.append("//     ES module registry under Node so the content matches upstream exactly)")
    lines.append("//")
    lines.append("// Regenerate with: python3 tools/generate_resources.py <path-to-uBlock-Origin-source>")
    lines.append("")
    lines.append("use adblock::resources::{MimeType, PermissionMask, Resource, ResourceType};")
    lines.append("")
    lines.append("/// Permission bit for uBO scriptlets flagged `requiresTrust` (e.g. trusted-set-cookie).")
    lines.append("/// No parsed filter list is currently granted this permission, so these scriptlets are")
    lines.append("/// registered for completeness but cannot be invoked yet. Wire this up to a per-filter-")
    lines.append("/// list \"trusted\" flag in the future if that's ever needed.")
    lines.append("pub const TRUSTED_SCRIPTLET: PermissionMask = PermissionMask::from_bits(0b0000_0001);")
    lines.append("")
    lines.append("/// Redirect stubs + scriptlets bundled from uBlock Origin, wired into the adblock-rust")
    lines.append("/// `Engine` via `Engine::use_resources()` so `$redirect=`/`$redirect-rule=` and `##+js(...)`")
    lines.append("/// rules resolve to real content instead of no-ops.")
    lines.append("pub fn bundled_resources() -> Vec<Resource> {")
    lines.append("    vec![")

    redirect_count = 0
    for e in redirects:
        name = e["name"]
        with open(os.path.join(war_dir, name), "rb") as f:
            content_b64 = base64.b64encode(f.read()).decode("ascii")
        lines.append("        Resource {")
        lines.append(f"            name: {rust_str(name)}.to_string(),")
        lines.append(f"            aliases: {rust_str_vec(e['aliases'])},")
        lines.append(f"            kind: ResourceType::Mime(MimeType::from_extension({rust_str(name)})),")
        lines.append(f"            content: {rust_str(content_b64)}.to_string(),")
        lines.append("            dependencies: vec![],")
        lines.append("            permission: Default::default(),")
        lines.append("        },")
        redirect_count += 1

    scriptlet_count = 0
    for s in scriptlets:
        name = s["name"]
        is_fn_helper = name.endswith(".fn")
        code_b64 = base64.b64encode(s["code"].encode("utf-8")).decode("ascii")
        kind = "MimeType::FnJavascript" if is_fn_helper else "MimeType::ApplicationJavascript"
        permission = "TRUSTED_SCRIPTLET" if s["requiresTrust"] else "Default::default()"
        lines.append("        Resource {")
        lines.append(f"            name: {rust_str(name)}.to_string(),")
        lines.append(f"            aliases: {rust_str_vec(s['aliases'])},")
        lines.append(f"            kind: ResourceType::Mime({kind}),")
        lines.append(f"            content: {rust_str(code_b64)}.to_string(),")
        lines.append(f"            dependencies: {rust_str_vec(s['dependencies'])},")
        lines.append(f"            permission: {permission},")
        lines.append("        },")
        scriptlet_count += 1

    lines.append("    ]")
    lines.append("}")
    lines.append("")
    lines.append(f"// {redirect_count} redirect resources, {scriptlet_count} scriptlet resources")

    with open(OUT_PATH, "w") as f:
        f.write("\n".join(lines))

    os.remove(scriptlets_out)
    os.remove(redirects_out)
    print(f"Wrote {OUT_PATH}: {redirect_count} redirect resources, {scriptlet_count} scriptlet resources")


if __name__ == "__main__":
    main()
